# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/metrics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/metrics.proto\x12\x11\x61watch.metrics.v1\"M\n\x06Metric\x12\x13\n\x0bmetric_type\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x0c\n\x04unit\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"\x9f\x01\n\x0bMetricBatch\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x12\n\nip_address\x18\x03 \x01(\t\x12*\n\x07metrics\x18\x04 \x03(\x0b\x32\x19.awatch.metrics.v1.Metric\x12\x14\n\x0c\x63ollected_at\x18\x05 \x01(\x03\x12\x16\n\x0e\x62\x61tch_sequence\x18\x06 \x01(\x04\"X\n\tStreamAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0e\x62\x61tch_sequence\x18\x03 \x01(\x04\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"&\n\x12HealthCheckRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"U\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x16\n\x0e\x62roker_version\x18\x02 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x03 \x01(\x03\"?\n\rErrorResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x03 \x01(\t2\xc1\x01\n\x0eMetricsService\x12Q\n\rStreamMetrics\x12\x1e.awatch.metrics.v1.MetricBatch\x1a\x1c.awatch.metrics.v1.StreamAck(\x01\x30\x01\x12\\\n\x0bHealthCheck\x12%.awatch.metrics.v1.HealthCheckRequest\x1a&.awatch.metrics.v1.HealthCheckResponseB.Z)github.com/awatch/agent/pkg/proto;metrics\x90\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.metrics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z)github.com/awatch/agent/pkg/proto;metrics\220\001\001'
  _METRIC._serialized_start=42
  _METRIC._serialized_end=119
  _METRICBATCH._serialized_start=122
  _METRICBATCH._serialized_end=281
  _STREAMACK._serialized_start=283
  _STREAMACK._serialized_end=371
  _HEALTHCHECKREQUEST._serialized_start=373
  _HEALTHCHECKREQUEST._serialized_end=411
  _HEALTHCHECKRESPONSE._serialized_start=413
  _HEALTHCHECKRESPONSE._serialized_end=498
  _ERRORRESPONSE._serialized_start=500
  _ERRORRESPONSE._serialized_end=563
  _METRICSSERVICE._serialized_start=566
  _METRICSSERVICE._serialized_end=759
_builder.BuildServices(DESCRIPTOR, 'proto.metrics_pb2', globals())
# @@protoc_insertion_point(module_scope)
