# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.proto import metrics_pb2 as proto_dot_metrics__pb2


class MetricsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamMetrics = channel.stream_stream(
                '/awatch.metrics.v1.MetricsService/StreamMetrics',
                request_serializer=proto_dot_metrics__pb2.MetricBatch.SerializeToString,
                response_deserializer=proto_dot_metrics__pb2.StreamAck.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/awatch.metrics.v1.MetricsService/HealthCheck',
                request_serializer=proto_dot_metrics__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=proto_dot_metrics__pb2.HealthCheckResponse.FromString,
                )


class MetricsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamMetrics(self, request_iterator, context):
        """Bidirectional streaming RPC for continuous metrics submission
        Client sends: stream of MetricBatch
        Server responds: stream of StreamAck
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Unary RPC for health checking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetricsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamMetrics': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamMetrics,
                    request_deserializer=proto_dot_metrics__pb2.MetricBatch.FromString,
                    response_serializer=proto_dot_metrics__pb2.StreamAck.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_metrics__pb2.HealthCheckRequest.FromString,
                    response_serializer=proto_dot_metrics__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'awatch.metrics.v1.MetricsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MetricsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamMetrics(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/awatch.metrics.v1.MetricsService/StreamMetrics',
            proto_dot_metrics__pb2.MetricBatch.SerializeToString,
            proto_dot_metrics__pb2.StreamAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/awatch.metrics.v1.MetricsService/HealthCheck',
            proto_dot_metrics__pb2.HealthCheckRequest.SerializeToString,
            proto_dot_metrics__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
